jwt:
  secret: zindagi

server:
  port: 1234

  servlet:
    context-path: /zindgi

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true
  datasource:
    url: jdbc:mysql://localhost:3306/Employee
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: true
  spring:
    devtools:
      restart:
        poll-interval: 10ms
        quiet-period: 5ms
      livereload:
        enabled: true

management:
  endpoints:
    jmx:
      exposure:
        include: '*'

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

